### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by DaveAtkinsonXMOS** [xmos/xcore_sdk#178]
Viewing the documentation via the github website on any browser or OS shows thefollowing

On main@69905e4, the "Getting Started Guide" link (https://github.com/xmos/aiot_sdk/blob/develop/documents/quick_start/getting-started.rst) under "Documentation is dead.

On develop@17a4931, in the Installation Guide link (https://github.com/xmos/xcore_sdk/blob/develop/documents/quick_start/installation.rst), under "System Requirements", the minimum system requirements and prerequisites look like links, but don't seem to point to a valid URL.

**Comment by keithm-xmos** [comment]
The documentation is not intended to be viewed from GitHub.   Some RST files will display fine, others will not.  Instead, HTML docs will be generated and hosted somewhere - much like with the XTC tools (https://www.xmos.ai/documentation/XM-014363-PC-5/html/).   Hosting has not been setup quite yet.  I have made a note in the documentation README to clarify.  

See https://github.com/xmos/xcore_sdk/pull/179

The "Getting Started Guide" link issue on the `main` branch will not be fixed as we are very close to staging a new release.
