### ISSUE TITLE
FreeRTOS CIFAR10 example build with USE_EXTMEM=1 doesn't work

### ISSUE THREAD

**Issue by thomasngxmos** [xmos/xcore_sdk#190]
OS: Ubuntu 18.04LTS
Board: Explorer
Commit SHA: b9b06b1c

Following README to make cifar10 example with USE_EXTMEM=1. The output binary is almost same as that without using this build option. Looks like the build option doesn't get propagated down to make process for individual tiles.

I will expect the USE_EXTMEM=1 flag will use __attribute__((section(".ExtMem_data"))) in cirfar10_model_data.c but it doesn't.

Similar behavour is observed on USE_SWMEM=1 too.

**Comment by keithm-xmos** [comment]
Hi Thomas,

I do not expect the output binary size to change necessarily with respect to the ExtMem or SwMem build configuration.  If and how it changes is a question best asked to someone on the XTC Tools team, like Mark or Jack.  However, you can observe that the resource usage report changes with each build configuration.  I have include snippets of the reports for each build config below:

**Default build config:**

```
Constraint check for tile[0]:
  Memory available:       524288,   used:      323052 .  OKAY
    (Stack: 5300, Code: 46672, Data: 271080)

Constraint check for tile[1]:
  Memory available:       524288,   used:      487476 .  OKAY
    (Stack: 5260, Code: 82760, Data: 399456)
```

**USE_EXTMEM=1 build config:**

```
Constraint check for tile[0]:
  Memory available:       524288,   used:      323052 .  OKAY
    (Stack: 5300, Code: 46672, Data: 271080)
  ExtMem available:    134217728,   used:          0 .  OKAY
    (Stack: 0, Code: 0, Data: 0)

Constraint check for tile[1]:
  Memory available:       524288,   used:      389284 .  OKAY
    (Stack: 5260, Code: 82760, Data: 301264)
  ExtMem available:    134217728,   used:      98192 .  OKAY
    (Stack: 0, Code: 0, Data: 98192)
```

**USE_SWMEM=1 build config:**

```
Constraint check for tile[0]:
  Memory available:       524288,   used:      323160 .  OKAY
    (Stack: 5300, Code: 46756, Data: 271104)
  SwMem available:    1073741824,   used:          0 .  OKAY
    (Stack: 0, Code: 0, Data: 0)

Constraint check for tile[1]:
  Memory available:       524288,   used:      391788 .  OKAY
    (Stack: 5260, Code: 84828, Data: 301700)
  SwMem available:    1073741824,   used:      98192 .  OKAY
    (Stack: 0, Code: 0, Data: 98192)
```

You can see from these reports how the tile[1] SRAM used is lower for the ExtMem and SwMem configs, and that the ExtMem and SwMem available  reflects this.

I hope this helps clarify.  DO not hesitate to ask if you have further questions. 

Cheers,
Keith
