### ISSUE TITLE
Convert HIL unit tests to no longer use `xmos_test` 

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/xcore_sdk#224]
They currently use `xmos_test` which is deprecated and only available to members of the XMOS organization. 

Most likely will update them to use pytest and https://github.com/xmos/test_support.

**Comment by ACascarino** [comment]
I've been working with lib_i2s and lib_i2c over the last couple of weeks and was looking into doing this in those repositories anyway - @keithm-xmos would you like me to pick this up on this repository?

**Comment by keithm-xmos** [comment]
@ACascarino That would be great!

**Comment by ACascarino** [comment]
@keithm-xmos Grand okay, will start plodding along with this then!
