### ISSUE TITLE
Makefile build in Windows yields errors

### ISSUE THREAD

**Issue by astewart-xmos** [xmos/xcore_sdk#246]
**System information**
 - OS: Windows 10
 - SDK commit:  959157bbad

Although not officially supported, currently the only thing preventing builds in windows using GnuMake seems to be the following two lines of tools/cmake_utils/multitile_build.cmake :

https://github.com/xmos/xcore_sdk/blob/develop/tools/cmake_utils/multitile_build.cmake#L21
https://github.com/xmos/xcore_sdk/blob/develop/tools/cmake_utils/multitile_build.cmake#L51

Both are cases of using a custom target to issue a command in a shell to create a new directory.

    ALL     mkdir -p ${CMAKE_CURRENT_SOURCE_DIR}/${OUTPUT_DIR}
    ...
    ALL     mkdir -p ${CMAKE_BINARY_DIR}/intermediates/${_TILE}
            
Windows has a `mkdir` command, but where on Linux the `-p` flag instructs `mkdir` to create and required parent directories, `mkdir` on Windows appears to do this by default, and it does not recognize the `-p` flag, causing the command to fail.

Additionally, whereas some commands in Windows will accept either forward- or back-slash characters as path separators, the Windows version of `mkdir` seems to want only the Windows-style `\` path separators.

Finally, `mkdir` in Windows also fails if the directory already exists, and there is no flag which prevents this.

The manual (Windows-only) solution was to change these two lines to the following:

    ALL   if not exist ${CMAKE_CURRENT_SOURCE_DIR}\\${OUTPUT_DIR}  mkdir ${CMAKE_CURRENT_SOURCE_DIR}\\${OUTPUT_DIR}
    ...
    ALL  if not exist ${CMAKE_BINARY_DIR}\\intermediates\\${_TILE} mkdir ${CMAKE_BINARY_DIR}\\intermediates\\${_TILE}

----

I suggest creating a CMake macro which assembles the appropriate command string for directory creation in a platform-aware way and using this where ever directory creation is required.

**Comment by keithm-xmos** [comment]
It appears CMake has a way to handle this in a platform-neutral way.  See: https://cmake.org/cmake/help/latest/command/file.html#make-directory
