### ISSUE TITLE
install_host_apps script builds but doesn't install.

### ISSUE THREAD

**Issue by eesctc** [xmos/xcore_sdk#338]
On Ubuntu 20.04.3 LTS this script correctly runs cmake/make and generates fatfs_mkimage in xcore_sdk/modules/rtos/sw_services/fatfs/host/build but does not seem to make any attempt to add or link to a /opt/xmos/... folder as suggested by this line and the installation documentation.

https://github.com/xmos/xcore_sdk/blob/843ca482157349ca358ced24e4a5743635a53a2f/tools/install/install_host_apps.sh#L19

Script output:
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring for GCC
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eesctc/ssd1306/xcore_sdk/modules/rtos/sw_services/fatfs/host/build
[ 11%] Building C object CMakeFiles/fatfs_mkimage.dir/src/fatfs_mkimage.c.o
[ 44%] Building C object CMakeFiles/fatfs_mkimage.dir/src/fatfs_ops.c.o
[ 44%] Building C object CMakeFiles/fatfs_mkimage.dir/src/directory_add.c.o
[ 44%] Building C object CMakeFiles/fatfs_mkimage.dir/src/ramdisk.c.o
[ 55%] Building C object CMakeFiles/fatfs_mkimage.dir/src/diskio.c.o
[ 66%] Building C object CMakeFiles/fatfs_mkimage.dir/src/ffsystem.c.o
[ 77%] Building C object CMakeFiles/fatfs_mkimage.dir/argtable/argtable3.c.o
[ 88%] Building C object CMakeFiles/fatfs_mkimage.dir/home/eesctc/ssd1306/xcore_sdk/modules/rtos/sw_services/fatfs/thirdparty/src/ff.c.o
[100%] Linking C executable fatfs_mkimage
[100%] Built target fatfs_mkimage

Utility executables created at /opt/xmos/SDK/version/bin/
Please add to the PATH system environment variable.

Then, test with: fatfs_mkimage --help

**Comment by keithm-xmos** [comment]
I wonder if the message is misleading because of the "version".  This script once put the binary in a folder like:

`/opt/xmos/SDK/0.11.1/bin/`

@xmos-jmccarthy  Where should this file go in the new build system?

**Comment by keithm-xmos** [comment]
@xmos-jmccarthy I now grok how this should work and will fix.  I withdraw my question.

**Comment by xmos-jmccarthy** [comment]
Yes.  These scripts should be obsoleted by 694065fa5a369ee23f1616f0cd9084f9cec54466.
As we discussed, there are some docs that need to reflect the new method to setup host apps and verified on Windows.

**Comment by keithm-xmos** [comment]
Fixed by https://github.com/xmos/xcore_sdk/pull/343
