### ISSUE TITLE
Bare metal examples build command needs toolchain info

### ISSUE THREAD

**Issue by chrisc-xmos** [xmos/xcore_sdk#341]
Thank you for submitting an SDK documentation issue. Please provide as much information you can.

**System information**
 - OS: Ubuntu 20.04.3 LTS
 - XCore board: Xcore-ai Explorer
 - commit 8c4f569e0498e89fc0ab84dbe9e1c30e7187bdcd

**Describe the documentation issue**
The explorer board bare metal examples readme (which propagates to the documentation) suggests building with:
cmake -B build
but this does not create the appropriate make targets on my system. I needed to do:
cmake -B build -DCMAKE_TOOLCHAIN_FILE=tools/cmake_utils/xmos_xs3a_toolchain.cmake

**Comment by keithm-xmos** [comment]
Fixed by https://github.com/xmos/xcore_sdk/pull/343
