### ISSUE TITLE
freertos explorer board example fails in run time

### ISSUE THREAD

**Issue by uvvpavel** [xmos/xcore_sdk#458]
While running freertos explorer_board example on my windows machine, I got this 
`Failed to open file /flash/fs/demo.txt
xrun: Program received signal ET_LOAD_STORE, Memory access exception.
      [Switching to tile[0] core[4]]
      outs (lp=0x0) at /home/paveluvarov/sandboxes/xcore_sdk/modules/core/modules/utils/src/xcore_printf.c:92
      92        /home/paveluvarov/sandboxes/xcore_sdk/modules/core/modules/utils/src/xcore_printf.c: No such file or directory.
        in /home/paveluvarov/sandboxes/xcore_sdk/modules/core/modules/utils/src/xcore_printf.c`

**Comment by keithm-xmos** [comment]
@uvvpavel, did you get any errors when you ran the step to flash the filesystem?

`make flash_fs_example_freertos_explorer_board`

or

`nmake flash_fs_example_freertos_explorer_board`

**Comment by uvvpavel** [comment]
Closing this issue, since I've been using xflash wrong
