### ISSUE TITLE
The RTOS HW test setup loops a 1v8 pin into a 3v3 pin

### ISSUE THREAD

**Issue by ed-xmos** [xmos/xcore_sdk#467]
The loopback:
GPIO I/O      X1D12 : X1D39

connects an IO on VIOL (3v3) to VDD18 (1v8). The GPIO test in test HIL drives from 1v8 to 3v3 which will not cause harm but result  in an unreliable high input. 

I found the issues when looping back the UART and driving 1Mbps @3v3 into a 1v8 port caused the chip to crash!

A series resistor and ensuring you drive X1D39-> X1D12 might be a quick work around.

**Comment by xmos-jmccarthy** [comment]
This rtos_driver hil tests are split across 2 apps currently.  We should move the GPIO test from rtos_drivers/hil to the rtos_driver/hil_add application, and move it to a different connection.  In both cases we should remove this jumper to prevent someone in the future from driving VDDIOL to VDD18.

This update should be 1 story point.

Another option would be to depopulate R35 and R37, and populating R36 and R38.  With this change all IO would be on the 1V8 power rail, and give us access to these 1b ports for intertile IO tests.
