### ISSUE TITLE
Dead link in README to documentation

### ISSUE THREAD

**Issue by xhuw** [xmos/xcore_sdk#496]
Thank you for submitting an SDK documentation issue. Please provide as much information you can.

**System information**

**Describe the documentation issue**

The link in the readme to the docs is dead:

look in section https://github.com/xmos/xcore_sdk#documentation
the link: https://www.xmos.ai/documentation/XM-014660-PC-2/html/

**Other information**

**Comment by keithm-xmos** [comment]
The link will work once the HTML documentation goes live.

**Comment by keithm-xmos** [comment]
Reopening as the HTML documentation did not go live today as planned.  Will close when it does.

**Comment by keithm-xmos** [comment]
Docs now live online
