### ISSUE TITLE
DFU OS Compatibility

### ISSUE THREAD

**Issue by xmos-jmccarthy** [xmos/xcore_sdk#553]
**System information**
 - OS: Windows
 - SDK version: Post #552 

**Describe the problem**
Needs verification on:
- [x] Windows
- [x] Mac

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Following instructions at:
https://github.com/xmos/xcore_sdk/blob/feature/dfu/examples/freertos/dfu/README.rst

**Other info or logs** 
Verified on Linux, Ubuntu 22

**Comment by keithm-xmos** [comment]
Once confirmed this works on Windows and MacOs, closes https://github.com/xmos/sln_voice/issues/12

**Comment by keithm-xmos** [comment]
I verified this works on MacOS.

**Comment by johnshaferXMOS** [comment]
Verified on Windows!
