### ISSUE TITLE
Independent tile building with extmem

### ISSUE THREAD

**Issue by xmos-jmccarthy** [xmos/xcore_sdk#70]
https://github.com/xmos/aiot_sdk/blob/c1e9d5b8199256a6875666e6651785c01df13264/examples/freertos/cifar10/src/main.c#L113-L124

This workaround is required for xmap to place the setup code for tile 1 extmem control in the tile 0 build.  This xmap issue is only a problem for independent tile building applications.  The code snippet above is not actually executed in the final resulting binary.

Future versions of the tools should provide a way to manually place extmem setup that is being done under the hood by xmap.  At this point, it should be revisited and resolved.

**Comment by keithm-xmos** [comment]
Completed.  Going forward, need to define the tile with ExtMem as the bast tile in the CMake build system.
